version: '3.9'

services:
  postgres:
    image: postgres:14
    container_name: fire-postgres
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: fire_detection
    ports:
      - "5432:5432"
    volumes:
      - fire_postgres_data:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4
    container_name: fire-pgadmin
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: mrtaivietbac@gmail.com
      PGADMIN_DEFAULT_PASSWORD: tester
    ports:
      - "5050:80"
    depends_on:
      - postgres

     # --- Service AI Python (Thêm mới) ---
  ai-service:
    build:
      context: ../fire-detection-ai-service # <<< Đường dẫn tới thư mục code AI service
      dockerfile: Dockerfile
    container_name: fire_ai_python
    ports:
      - "5001:5001"
    environment:
      - PORT=5001
      - MODEL_PATH=/app/fire_detection_model.h5
      - IMG_SIZE=256
      - TZ=Asia/Ho_Chi_Minh
    volumes:
      - ai_logs:/app/logs
    restart: unless-stopped
volumes:
  fire_postgres_data:
  ai_logs:
